add search but fails with auth error
````
Traceback (most recent call last):
  File "/Users/mxm/Code/mine/geo_worktrees/satellite_spikes/spikes/satellite/eopf-stac-python/main.py", line 59, in <module>
    main()
    ~~~~^^
  File "/Users/mxm/Code/mine/geo_worktrees/satellite_spikes/spikes/satellite/eopf-stac-python/main.py", line 39, in main
    time_items = list_found_elements(time_frame)
  File "/Users/mxm/Code/mine/geo_worktrees/satellite_spikes/spikes/satellite/eopf-stac-python/main.py", line 52, in list_found_elements
    for item in search_result.items():  # retrieves the result inside the catalogue.
                ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/mxm/Code/mine/geo_worktrees/satellite_spikes/spikes/satellite/eopf-stac-python/.venv/lib/python3.13/site-packages/pystac_client/item_search.py", line 785, in items
    for item in self.items_as_dicts():
                ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/mxm/Code/mine/geo_worktrees/satellite_spikes/spikes/satellite/eopf-stac-python/.venv/lib/python3.13/site-packages/pystac_client/item_search.py", line 796, in items_as_dicts
    for page in self.pages_as_dicts():
                ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/mxm/Code/mine/geo_worktrees/satellite_spikes/spikes/satellite/eopf-stac-python/.venv/lib/python3.13/site-packages/pystac_client/item_search.py", line 826, in pages_as_dicts
    for page in self._stac_io.get_pages(
                ~~~~~~~~~~~~~~~~~~~~~~~^
        self.url, self.method, self.get_parameters()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ):
    ^
  File "/Users/mxm/Code/mine/geo_worktrees/satellite_spikes/spikes/satellite/eopf-stac-python/.venv/lib/python3.13/site-packages/pystac_client/stac_api_io.py", line 304, in get_pages
    page = self.read_json(url, method=method, parameters=parameters)
  File "/Users/mxm/Code/mine/geo_worktrees/satellite_spikes/spikes/satellite/eopf-stac-python/.venv/lib/python3.13/site-packages/pystac/stac_io.py", line 206, in read_json
    txt = self.read_text(source, *args, **kwargs)
  File "/Users/mxm/Code/mine/geo_worktrees/satellite_spikes/spikes/satellite/eopf-stac-python/.venv/lib/python3.13/site-packages/pystac_client/stac_api_io.py", line 167, in read_text
    return self.request(href, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mxm/Code/mine/geo_worktrees/satellite_spikes/spikes/satellite/eopf-stac-python/.venv/lib/python3.13/site-packages/pystac_client/stac_api_io.py", line 219, in request
    raise APIError.from_response(resp)
pystac_client.exceptions.APIError: {"message":"Missing authorization in request"}
````